FROM python/3.10.4-slim-buster

RUN apt-get -yq update \
	&& apt-get -yq upgrade

RUN wget -q -O - http://archives.fledge-iot.org/KEY.gpg | sudo apt-key add -

RUN echo "deb  http://archives.fledge-iot.org/latest/buster/armv7l/ /" >> /etc/apt/sources.list

RUN apt -yq update \
	&& apt -yq install fledge
